const menuItems = [
  "All Categories",
  "Deals",
  "Alexa Skills",
  "Amazon Devices",
  "Amazon Fashion",
  "Amazon Fresh",
  "Amazon Pantry",
  "Appliences",
  "Apps & Games",
  "Baby",
  "Beauty",
  "Books",
  "Car & Motorbike",
  "Clothing & Accessories",
  "Collectibles",
  "Computers & Accessories",
  "Electronics",
  "Furniture",
  "Garden & Outdoors",
  "Gift Cards",
  "Grocery & Gourmet Foods",
  "Health & Personal Care",
  "Home & Kitchen",
  "Industrial & Scientific",
  "Jewellery",
  "Kindle Store",
  "Luggage & Bags",
  "Luxury Beauty",
  "Movies & TV Shows",
  "Music",
  "Musical Instruments",
  "Office Products",
  "Pet Supplies",
  "Prime Video",
  "Shoes & Handbags",
  "Software",
  "Sports, Fitness & Outdoors",
  "Tools & Home Improvement",
  "Toys & Games",
  "Under ₹500",
  "Video Games",
  "Watches",
];
const subMenuItems = [
  "Best Sellers",
  "Mobiles",
  "Today's Deals",
  "Fashion",
  "New Releases",
  "Prime",
  "Electronics",
  "Customer Service",
  "Amazon Pay",
  "Home & Kitchen",
];
export { menuItems, subMenuItems };
